// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects.models;

/**
 * The Type (or category) of the connection.
 */
public enum ConnectionType {
    /**
     * Azure OpenAI Service.
     */
    AZURE_OPEN_AI("AzureOpenAI"),

    /**
     * Serverless API Service.
     */
    SERVERLESS("Serverless"),

    /**
     * Azure Blob Storage.
     */
    AZURE_BLOB_STORAGE("AzureBlob"),

    /**
     * Azure AI Services.
     */
    AZURE_AISERVICES("AIServices"),

    /**
     * Azure AI Search.
     */
    AZURE_AISEARCH("CognitiveSearch"),

    /**
     * Generic connection that uses API Key authentication.
     */
    APIKEY("ApiKey");

    /**
     * The actual serialized value for a ConnectionType instance.
     */
    private final String value;

    ConnectionType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ConnectionType instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed ConnectionType object, or null if unable to parse.
     */
    public static ConnectionType fromString(String value) {
        if (value == null) {
            return null;
        }
        ConnectionType[] items = ConnectionType.values();
        for (ConnectionType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
