// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * List View Type Definition.
 */
public final class ListViewType extends ExpandableStringEnum<ListViewType> {
    /**
     * List only active items.
     */
    @Generated
    public static final ListViewType ACTIVE_ONLY = fromString("ActiveOnly");

    /**
     * List only archived items.
     */
    @Generated
    public static final ListViewType ARCHIVED_ONLY = fromString("ArchivedOnly");

    /**
     * List all items.
     */
    @Generated
    public static final ListViewType ALL = fromString("All");

    /**
     * Creates a new instance of ListViewType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public ListViewType() {
    }

    /**
     * Creates or finds a ListViewType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ListViewType.
     */
    @Generated
    public static ListViewType fromString(String name) {
        return fromString(name, ListViewType.class);
    }

    /**
     * Gets known ListViewType values.
     * 
     * @return known ListViewType values.
     */
    @Generated
    public static Collection<ListViewType> values() {
        return values(ListViewType.class);
    }
}
