// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Red team details.
 */
@Fluent
public final class RedTeam implements JsonSerializable<RedTeam> {
    /*
     * Identifier of the red team.
     */
    @Generated
    private String id;

    /*
     * Name of the red-team scan.
     */
    @Generated
    private String scanName;

    /*
     * Number of simulation rounds.
     */
    @Generated
    private final int numTurns;

    /*
     * List of attack strategies or nested lists of attack strategies.
     */
    @Generated
    private final List<AttackStrategy> attackStrategies;

    /*
     * Simulation-only or Simulation + Evaluation. Default false, if true the scan outputs conversation not evaluation
     * result.
     */
    @Generated
    private final boolean simulationOnly;

    /*
     * List of risk categories to generate attack objectives for.
     */
    @Generated
    private final List<RiskCategory> riskCategories;

    /*
     * Application scenario for the red team operation, to generate scenario specific attacks.
     */
    @Generated
    private String applicationScenario;

    /*
     * Red team's tags. Unlike properties, tags are fully mutable.
     */
    @Generated
    private Map<String, String> tags;

    /*
     * Red team's properties. Unlike tags, properties are add-only. Once added, a property cannot be removed.
     */
    @Generated
    private Map<String, String> properties;

    /*
     * Status of the red-team. It is set by service and is read-only.
     */
    @Generated
    private String status;

    /*
     * Target configuration for the red-team run.
     */
    @Generated
    private final TargetConfig targetConfig;

    /**
     * Creates an instance of RedTeam class.
     * 
     * @param numTurns the numTurns value to set.
     * @param attackStrategies the attackStrategies value to set.
     * @param simulationOnly the simulationOnly value to set.
     * @param riskCategories the riskCategories value to set.
     * @param targetConfig the targetConfig value to set.
     */
    @Generated
    public RedTeam(int numTurns, List<AttackStrategy> attackStrategies, boolean simulationOnly,
        List<RiskCategory> riskCategories, TargetConfig targetConfig) {
        this.numTurns = numTurns;
        this.attackStrategies = attackStrategies;
        this.simulationOnly = simulationOnly;
        this.riskCategories = riskCategories;
        this.targetConfig = targetConfig;
    }

    /**
     * Get the id property: Identifier of the red team.
     * 
     * @return the id value.
     */
    @Generated
    public String getId() {
        return this.id;
    }

    /**
     * Get the scanName property: Name of the red-team scan.
     * 
     * @return the scanName value.
     */
    @Generated
    public String getScanName() {
        return this.scanName;
    }

    /**
     * Set the scanName property: Name of the red-team scan.
     * 
     * @param scanName the scanName value to set.
     * @return the RedTeam object itself.
     */
    @Generated
    public RedTeam setScanName(String scanName) {
        this.scanName = scanName;
        return this;
    }

    /**
     * Get the numTurns property: Number of simulation rounds.
     * 
     * @return the numTurns value.
     */
    @Generated
    public int getNumTurns() {
        return this.numTurns;
    }

    /**
     * Get the attackStrategies property: List of attack strategies or nested lists of attack strategies.
     * 
     * @return the attackStrategies value.
     */
    @Generated
    public List<AttackStrategy> getAttackStrategies() {
        return this.attackStrategies;
    }

    /**
     * Get the simulationOnly property: Simulation-only or Simulation + Evaluation. Default false, if true the scan
     * outputs conversation not evaluation result.
     * 
     * @return the simulationOnly value.
     */
    @Generated
    public boolean isSimulationOnly() {
        return this.simulationOnly;
    }

    /**
     * Get the riskCategories property: List of risk categories to generate attack objectives for.
     * 
     * @return the riskCategories value.
     */
    @Generated
    public List<RiskCategory> getRiskCategories() {
        return this.riskCategories;
    }

    /**
     * Get the applicationScenario property: Application scenario for the red team operation, to generate scenario
     * specific attacks.
     * 
     * @return the applicationScenario value.
     */
    @Generated
    public String getApplicationScenario() {
        return this.applicationScenario;
    }

    /**
     * Set the applicationScenario property: Application scenario for the red team operation, to generate scenario
     * specific attacks.
     * 
     * @param applicationScenario the applicationScenario value to set.
     * @return the RedTeam object itself.
     */
    @Generated
    public RedTeam setApplicationScenario(String applicationScenario) {
        this.applicationScenario = applicationScenario;
        return this;
    }

    /**
     * Get the tags property: Red team's tags. Unlike properties, tags are fully mutable.
     * 
     * @return the tags value.
     */
    @Generated
    public Map<String, String> getTags() {
        return this.tags;
    }

    /**
     * Set the tags property: Red team's tags. Unlike properties, tags are fully mutable.
     * 
     * @param tags the tags value to set.
     * @return the RedTeam object itself.
     */
    @Generated
    public RedTeam setTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * Get the properties property: Red team's properties. Unlike tags, properties are add-only. Once added, a property
     * cannot be removed.
     * 
     * @return the properties value.
     */
    @Generated
    public Map<String, String> getProperties() {
        return this.properties;
    }

    /**
     * Set the properties property: Red team's properties. Unlike tags, properties are add-only. Once added, a property
     * cannot be removed.
     * 
     * @param properties the properties value to set.
     * @return the RedTeam object itself.
     */
    @Generated
    public RedTeam setProperties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the status property: Status of the red-team. It is set by service and is read-only.
     * 
     * @return the status value.
     */
    @Generated
    public String getStatus() {
        return this.status;
    }

    /**
     * Get the targetConfig property: Target configuration for the red-team run.
     * 
     * @return the targetConfig value.
     */
    @Generated
    public TargetConfig getTargetConfig() {
        return this.targetConfig;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeIntField("numTurns", this.numTurns);
        jsonWriter.writeArrayField("attackStrategies", this.attackStrategies,
            (writer, element) -> writer.writeString(element == null ? null : element.toString()));
        jsonWriter.writeBooleanField("simulationOnly", this.simulationOnly);
        jsonWriter.writeArrayField("riskCategories", this.riskCategories,
            (writer, element) -> writer.writeString(element == null ? null : element.toString()));
        jsonWriter.writeJsonField("targetConfig", this.targetConfig);
        jsonWriter.writeStringField("scanName", this.scanName);
        jsonWriter.writeStringField("applicationScenario", this.applicationScenario);
        jsonWriter.writeMapField("tags", this.tags, (writer, element) -> writer.writeString(element));
        jsonWriter.writeMapField("properties", this.properties, (writer, element) -> writer.writeString(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RedTeam from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RedTeam if the JsonReader was pointing to an instance of it, or null if it was pointing to
     * JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RedTeam.
     */
    @Generated
    public static RedTeam fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String id = null;
            int numTurns = 0;
            List<AttackStrategy> attackStrategies = null;
            boolean simulationOnly = false;
            List<RiskCategory> riskCategories = null;
            TargetConfig targetConfig = null;
            String scanName = null;
            String applicationScenario = null;
            Map<String, String> tags = null;
            Map<String, String> properties = null;
            String status = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    id = reader.getString();
                } else if ("numTurns".equals(fieldName)) {
                    numTurns = reader.getInt();
                } else if ("attackStrategies".equals(fieldName)) {
                    attackStrategies = reader.readArray(reader1 -> AttackStrategy.fromString(reader1.getString()));
                } else if ("simulationOnly".equals(fieldName)) {
                    simulationOnly = reader.getBoolean();
                } else if ("riskCategories".equals(fieldName)) {
                    riskCategories = reader.readArray(reader1 -> RiskCategory.fromString(reader1.getString()));
                } else if ("targetConfig".equals(fieldName)) {
                    targetConfig = TargetConfig.fromJson(reader);
                } else if ("scanName".equals(fieldName)) {
                    scanName = reader.getString();
                } else if ("applicationScenario".equals(fieldName)) {
                    applicationScenario = reader.getString();
                } else if ("tags".equals(fieldName)) {
                    tags = reader.readMap(reader1 -> reader1.getString());
                } else if ("properties".equals(fieldName)) {
                    properties = reader.readMap(reader1 -> reader1.getString());
                } else if ("status".equals(fieldName)) {
                    status = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            RedTeam deserializedRedTeam
                = new RedTeam(numTurns, attackStrategies, simulationOnly, riskCategories, targetConfig);
            deserializedRedTeam.id = id;
            deserializedRedTeam.scanName = scanName;
            deserializedRedTeam.applicationScenario = applicationScenario;
            deserializedRedTeam.tags = tags;
            deserializedRedTeam.properties = properties;
            deserializedRedTeam.status = status;

            return deserializedRedTeam;
        });
    }
}
