// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects;

import com.azure.ai.projects.implementation.IndexesImpl;
import com.azure.ai.projects.models.Index;
import com.azure.ai.projects.models.ListViewType;
import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;

/**
 * Initializes a new instance of the synchronous AIProjectClient type.
 */
@ServiceClient(builder = AIProjectClientBuilder.class)
public final class IndexesClient {
    @Generated
    private final IndexesImpl serviceClient;

    /**
     * Initializes an instance of IndexesClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    IndexesClient(IndexesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * List all versions of the given Index.
     * <p><strong>Query Parameters</strong></p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     * <tr><td>top</td><td>Integer</td><td>No</td><td>Top count of results, top count cannot be greater than the page
     * size. If topCount &gt; page size, results with be default page size count will be returned</td></tr>
     * <tr><td>skip</td><td>String</td><td>No</td><td>Continuation token for pagination.</td></tr>
     * <tr><td>tags</td><td>String</td><td>No</td><td>Comma-separated list of tag names (and optionally values).
     * Example: tag1,tag2=value2</td></tr>
     * <tr><td>listViewType</td><td>String</td><td>No</td><td>[ListViewType.ActiveOnly, ListViewType.ArchivedOnly,
     * ListViewType.All] View type for including/excluding (for example) archived entities. Allowed values:
     * "ActiveOnly", "ArchivedOnly", "All".</td></tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     type: String(AzureSearch/CosmosDBNoSqlVectorStore/ManagedAzureSearch) (Required)
     *     stage: String (Optional)
     *     id: String (Optional)
     *     name: String (Required)
     *     version: String (Required)
     *     description: String (Optional)
     *     tags (Optional): {
     *         String: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param name The name of the resource.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> listVersions(String name, RequestOptions requestOptions) {
        return this.serviceClient.listVersions(name, requestOptions);
    }

    /**
     * List the latest version of each Index.
     * <p><strong>Query Parameters</strong></p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     * <tr><td>top</td><td>Integer</td><td>No</td><td>Top count of results, top count cannot be greater than the page
     * size. If topCount &gt; page size, results with be default page size count will be returned</td></tr>
     * <tr><td>skip</td><td>String</td><td>No</td><td>Continuation token for pagination.</td></tr>
     * <tr><td>tags</td><td>String</td><td>No</td><td>Comma-separated list of tag names (and optionally values).
     * Example: tag1,tag2=value2</td></tr>
     * <tr><td>listViewType</td><td>String</td><td>No</td><td>[ListViewType.ActiveOnly, ListViewType.ArchivedOnly,
     * ListViewType.All] View type for including/excluding (for example) archived entities. Allowed values:
     * "ActiveOnly", "ArchivedOnly", "All".</td></tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     type: String(AzureSearch/CosmosDBNoSqlVectorStore/ManagedAzureSearch) (Required)
     *     stage: String (Optional)
     *     id: String (Optional)
     *     name: String (Required)
     *     version: String (Required)
     *     description: String (Optional)
     *     tags (Optional): {
     *         String: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<BinaryData> listLatest(RequestOptions requestOptions) {
        return this.serviceClient.listLatest(requestOptions);
    }

    /**
     * Get the specific version of the Index.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     type: String(AzureSearch/CosmosDBNoSqlVectorStore/ManagedAzureSearch) (Required)
     *     stage: String (Optional)
     *     id: String (Optional)
     *     name: String (Required)
     *     version: String (Required)
     *     description: String (Optional)
     *     tags (Optional): {
     *         String: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param name The name of the resource.
     * @param version The specific version id of the Index to retrieve.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the specific version of the Index along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> getVersionWithResponse(String name, String version, RequestOptions requestOptions) {
        return this.serviceClient.getVersionWithResponse(name, version, requestOptions);
    }

    /**
     * Delete the specific version of the Index.
     * 
     * @param name The name of the resource.
     * @param version The version of the Index to delete.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> deleteVersionWithResponse(String name, String version, RequestOptions requestOptions) {
        return this.serviceClient.deleteVersionWithResponse(name, version, requestOptions);
    }

    /**
     * Create a new or update an existing Index with the given version id.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     type: String(AzureSearch/CosmosDBNoSqlVectorStore/ManagedAzureSearch) (Required)
     *     stage: String (Optional)
     *     id: String (Optional)
     *     name: String (Required)
     *     version: String (Required)
     *     description: String (Optional)
     *     tags (Optional): {
     *         String: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     type: String(AzureSearch/CosmosDBNoSqlVectorStore/ManagedAzureSearch) (Required)
     *     stage: String (Optional)
     *     id: String (Optional)
     *     name: String (Required)
     *     version: String (Required)
     *     description: String (Optional)
     *     tags (Optional): {
     *         String: String (Required)
     *     }
     * }
     * }
     * </pre>
     * 
     * @param name The name of the resource.
     * @param version The specific version id of the Index to create or replace.
     * @param body The definition of the Index to create or update.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return index resource Definition along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createOrUpdateVersionWithResponse(String name, String version, BinaryData body,
        RequestOptions requestOptions) {
        return this.serviceClient.createOrUpdateVersionWithResponse(name, version, body, requestOptions);
    }

    /**
     * List all versions of the given Index.
     * 
     * @param name The name of the resource.
     * @param top Top count of results, top count cannot be greater than the page size. If topCount &gt; page size,
     * results with be default page size count will be returned.
     * @param skip Continuation token for pagination.
     * @param tags Comma-separated list of tag names (and optionally values). Example: tag1,tag2=value2.
     * @param listViewType [ListViewType.ActiveOnly, ListViewType.ArchivedOnly, ListViewType.All] View type for
     * including/excluding (for example) archived entities.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<Index> listVersions(String name, Integer top, String skip, String tags,
        ListViewType listViewType) {
        // Generated convenience method for listVersions
        RequestOptions requestOptions = new RequestOptions();
        if (top != null) {
            requestOptions.addQueryParam("top", String.valueOf(top), false);
        }
        if (skip != null) {
            requestOptions.addQueryParam("skip", skip, false);
        }
        if (tags != null) {
            requestOptions.addQueryParam("tags", tags, false);
        }
        if (listViewType != null) {
            requestOptions.addQueryParam("listViewType", listViewType.toString(), false);
        }
        return serviceClient.listVersions(name, requestOptions)
            .mapPage(bodyItemValue -> bodyItemValue.toObject(Index.class));
    }

    /**
     * List all versions of the given Index.
     * 
     * @param name The name of the resource.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<Index> listVersions(String name) {
        // Generated convenience method for listVersions
        RequestOptions requestOptions = new RequestOptions();
        return serviceClient.listVersions(name, requestOptions)
            .mapPage(bodyItemValue -> bodyItemValue.toObject(Index.class));
    }

    /**
     * List the latest version of each Index.
     * 
     * @param top Top count of results, top count cannot be greater than the page size. If topCount &gt; page size,
     * results with be default page size count will be returned.
     * @param skip Continuation token for pagination.
     * @param tags Comma-separated list of tag names (and optionally values). Example: tag1,tag2=value2.
     * @param listViewType [ListViewType.ActiveOnly, ListViewType.ArchivedOnly, ListViewType.All] View type for
     * including/excluding (for example) archived entities.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<Index> listLatest(Integer top, String skip, String tags, ListViewType listViewType) {
        // Generated convenience method for listLatest
        RequestOptions requestOptions = new RequestOptions();
        if (top != null) {
            requestOptions.addQueryParam("top", String.valueOf(top), false);
        }
        if (skip != null) {
            requestOptions.addQueryParam("skip", skip, false);
        }
        if (tags != null) {
            requestOptions.addQueryParam("tags", tags, false);
        }
        if (listViewType != null) {
            requestOptions.addQueryParam("listViewType", listViewType.toString(), false);
        }
        return serviceClient.listLatest(requestOptions).mapPage(bodyItemValue -> bodyItemValue.toObject(Index.class));
    }

    /**
     * List the latest version of each Index.
     * 
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return paged collection of Index items as paginated response with {@link PagedIterable}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<Index> listLatest() {
        // Generated convenience method for listLatest
        RequestOptions requestOptions = new RequestOptions();
        return serviceClient.listLatest(requestOptions).mapPage(bodyItemValue -> bodyItemValue.toObject(Index.class));
    }

    /**
     * Get the specific version of the Index.
     * 
     * @param name The name of the resource.
     * @param version The specific version id of the Index to retrieve.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the specific version of the Index.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Index getVersion(String name, String version) {
        // Generated convenience method for getVersionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return getVersionWithResponse(name, version, requestOptions).getValue().toObject(Index.class);
    }

    /**
     * Delete the specific version of the Index.
     * 
     * @param name The name of the resource.
     * @param version The version of the Index to delete.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void deleteVersion(String name, String version) {
        // Generated convenience method for deleteVersionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        deleteVersionWithResponse(name, version, requestOptions).getValue();
    }

    /**
     * Create a new or update an existing Index with the given version id.
     * 
     * @param name The name of the resource.
     * @param version The specific version id of the Index to create or replace.
     * @param body The definition of the Index to create or update.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return index resource Definition.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Index createOrUpdateVersion(String name, String version, Index body) {
        // Generated convenience method for createOrUpdateVersionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createOrUpdateVersionWithResponse(name, version, BinaryData.fromObject(body), requestOptions).getValue()
            .toObject(Index.class);
    }
}
