// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.projects.implementation.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The input definition information for a Microsoft Fabric tool as used to configure an agent.
 */
@Immutable
public final class MicrosoftFabricToolDefinition extends ToolDefinition {
    /*
     * The object type.
     */
    @Generated
    private String type = "fabric_aiskill";

    /*
     * The list of connections used by the Microsoft Fabric tool.
     */
    @Generated
    private final ToolConnectionList fabricAiskill;

    /**
     * Creates an instance of MicrosoftFabricToolDefinition class.
     * 
     * @param fabricAiskill the fabricAiskill value to set.
     */
    @Generated
    public MicrosoftFabricToolDefinition(ToolConnectionList fabricAiskill) {
        this.fabricAiskill = fabricAiskill;
    }

    /**
     * Get the type property: The object type.
     * 
     * @return the type value.
     */
    @Generated
    @Override
    public String getType() {
        return this.type;
    }

    /**
     * Get the fabricAiskill property: The list of connections used by the Microsoft Fabric tool.
     * 
     * @return the fabricAiskill value.
     */
    @Generated
    public ToolConnectionList getFabricAiskill() {
        return this.fabricAiskill;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("fabric_aiskill", this.fabricAiskill);
        jsonWriter.writeStringField("type", this.type);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MicrosoftFabricToolDefinition from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of MicrosoftFabricToolDefinition if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the MicrosoftFabricToolDefinition.
     */
    @Generated
    public static MicrosoftFabricToolDefinition fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ToolConnectionList fabricAiskill = null;
            String type = "fabric_aiskill";
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("fabric_aiskill".equals(fieldName)) {
                    fabricAiskill = ToolConnectionList.fromJson(reader);
                } else if ("type".equals(fieldName)) {
                    type = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            MicrosoftFabricToolDefinition deserializedMicrosoftFabricToolDefinition
                = new MicrosoftFabricToolDefinition(fabricAiskill);
            deserializedMicrosoftFabricToolDefinition.type = type;

            return deserializedMicrosoftFabricToolDefinition;
        });
    }
}
