// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.azure.ai.projects {
    requires com.azure.storage.blob;

    exports com.azure.ai.projects;
    exports com.azure.ai.projects.models;

    opens com.azure.ai.projects.models to com.azure.core;
}
